language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
- nvm install node
- npm install -g @angular/cli
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
before_deploy:
- git clone https://$ACCESS_TOKEN@github.com/MatthiasHerzog2000/bfk-portal-client.git
- cd ./bfk-portal-client
- ng build --prod
- copy ./dist ../bfk-portal-server/BfkPortal.Web/wwwroot
- cd ..
- rm -r ./bfk-portal-client
deploy:
  provider: heroku
  api_key: $API_KEY
  app: bfk-portal
  on:
    repo: ChristophThiel/bfk-portal-server