sudo: required

language: csharp

services:
 - docker

mono: none
dotnet: 2.1.403

install:
 - dotnet restore
 - wget -qO- https://toolbelt.heroku.com/install.sh | sh
# - nvm install node
# - npm install -g heroku
# - npm install -g @angular/cli

script:
 - dotnet build
# - dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
# - dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
 - /usr/local/bin/heroku restart --app bfk-portal
 - cd BfkPortal.Web
 - dotnet publish -c Release
# - cp Dockerfile ./bin/Release/netcoreapp2.1/publish
 - docker build -t bfk-portal .
 - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
 - docker tag bfk-portal registry.heroku.com/bfk-portal/web
 - docker push registry.heroku.com/bfk-portal/web
 - heroku container:release web --app bfk-portal