sudo: required

language: csharp

services:
 - docker

mono: none
dotnet: 2.1.403

install:
 - dotnet restore
# - nvm install node
# - npm install -g @angular/cli
 
script:
 - dotnet build
 - dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
 - dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
 - cd BfkPortal.Web
 - dotnet publish -c Release
 - cp Dockerfile ./bin/Release/netcoreapp2.1/publish
 - docker build -t bfk-portal .
 - docker tag bfk-portal registry.heroku.com/bfk-portal/web
 
deploy:
 provider: script
 script: bash ./deploy.sh
 on:
  branch: master
# - git clone https://$ACCESS_TOKEN@github.com/MatthiasHerzog2000/bfk-portal-client.git
# - cd ./bfk-portal-client
# - npm install --save-dev @angular-devkit/build-angular
# - ng build --prod --source-map=false
# - cd ..
# - cp -R ./bfk-portal-client/dist/mdb-angular-pro/ ./BfkPortal.Web/wwwroot/dist/
 
#before_deploy:
# - git clone https://$ACCESS_TOKEN@github.com/MatthiasHerzog2000/bfk-portal-client.git
# - cd ./bfk-portal-client
# - npm install --save-dev @angular-devkit/build-angular
# - ng build --prod --source-map=false
# - cd ..
# - cp -R ./bfk-portal-client/dist/mdb-angular-pro/ ./BfkPortal.Web/wwwroot/dist/
 
#deploy:
#  provider: heroku
#  api_key: $API_KEY
#  app: bfk-portal
#  on:
#    repo: ChristophThiel/bfk-portal-server
