language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
deploy:
  provider: heroku
  api_key: $API_KEY
  app: bfk-portal
  on:
    repo: ChristophThiel/bfk-portal-server