language: csharp
solution: BfkPortal.sln
install:
 - nuget restore BfkPortal.sln
 - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
mono: none
dotnet: 2.1.4
script:
 - xbuild /p:Configuration=Release BfkPortal.sln
 - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./BfkPortal.PersistenceTest/bin/Release/BfkPortal.PersistenceTest.dll