language: csharp
dist: trusty
mono: none
dotnet: 2.1.403

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
 - dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj