language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
deploy:
  provider: heroku
  api_key:
   - secure: bm9mux45O+P9Q7UVsMaaE2r/VIU2UePl79LFyzsRSKdzR1fRN8QYi7h864iYPp0fKJuvE5r2885oiAzBSXV17rLr9BD0GIDs+7liffzV9L2Io/ruM50WmXKq9FXEiXwQ07pU7p02YF/8zco+Q8Lp/skbOKWNk9B5q4fO0Efq75Salu5oE+6PDEhd7pl/urL0HRC0Rcek8ss8U3Bhhjn7Kd+8WwvRZOSS+E9UNOfBM3CT5O2VZF+3Yuw88jcWHqDGOxzk6veP4b1vvlhbk+G1+jl9JEvFPxAar/EZfL28m2x3wpKABXhn/1D/mumTerYMw32cwzBQGN1PyvAONjkm1OHUUKnoze9HFlIIVe95y9ogJfX5Pfv+roouGjClYPsu5YEDXTVt5KVfhicXgUDZH03HT9Dq78yqTuvr6uLzcS4g7VCVbeBC9M+RceVmuX1GLrVm+wuyUau0Ipo6NRCEJ0hDAot4W5AnnsMsruQiQr1O4B092yQWaVnsj+QObHCFrrgwVRkZlS38zxpBbgk4r54WY73adoWtOgSSJavIW+4s20SyJTj2OUkW2fUtUnzuwdVhU/A5qMTpZaMDeqPdQs9WuwaBdjS6XgUBT1Twv1EpZwRAXcui96x5kpHxsYAufvgs2j2+WczC6qbHs7o4pLN4sYn6ewCE7DlPm+V7x2c=
  app: bfk-portal
