language: csharp
dist: trusty
mono: none
dotnet: 2.1.403

install:
 - dotnet restore

script:
 - dotnet build
 - dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
 - dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
 
deploy:
    provider: heroku
    api_key: 60c16ffd-502d-4945-8df4-127a752b3937
    app: bfk-portal
    run:
     - "dotnet run -p BfkPortal.Web/BfkPortal.Web.csproj"