language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
deploy:
  provider: heroku
  api_key:
    secure: E/6J9FJRrC4YLNcpgFQcB6qUqgcCGgmAW2fqrIUuKFaFji9GVV27MdwDcHVK2z6WuGOxFtm4jjowJO3z88wqh/ti8W8NO0UdxOAZnKnexosBVeWGCGFKUBvEzy5QGxUGnYGSjGMFIiRalxh5Eott588Eu41q/v+0r5IrSudwld5eEh+yz4ApxXLUpc83Wh46mX2/AkCw4p3u+aq15Siv+JwqHRGCBnlcymXyzryFRKO9McKIbrLYDnw0z4SUVXetnpnd1apsLCA1cvu3Oc+vGY7fZnzLZUltaEo8c6p1LR8Nqfq+P0mb3ACPmAHz5FWAEKuYP9VrdCiKopyM/4j6VkeQViQmlacAJnZYISnYOpJw5wKqFOUwViGX4ngOHwe0rofNcFYGeuhr44d86SQRERMXLkHbNIxSq/sCjkRCogwrFp6xk8bAqEUoe6VR7LC0GX8zCYxzKHc82gr7Kkyiq4dL9L88ZwanFA+dEHrEL9jXvKnEvx7zky/t2hQgiUBBBFAHBHw10K2CzwQNTb7NYJM2z33yZRi9I3VGhppHkZSNcoUdj/fsxq+9evUvvZnziQESSi//HvNtbXhzyH3H2X/yneKgUpJ1N/w6iX3zoXcjdryg0UpbeKVPbMSOd/GJ+qYDVvQYnAPsK6+pJqaLL7d5r62ar37RX1iovabalU0=
  app: bfk-portal
