language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
deploy:
  provider: heroku
  api_key:
    secure: c9b/XVjH4rdtY1+SOIrdirdbJMSuIqaiL+715IGRbV+f+hC8puzv4Vlb8vtiLYwoiV5iMhlh6U7n/YctPL9V9rQZag2JByNGSXuVu83opiv3TJdcSwF0W3uAIoNvbcGWdO/5BgM0zVQRb8ZnuNPlSlbE34vM/zXWODh1PaYHZ6js4v0HhFKk/GRIkb9TaNdBfbeiqCbh/HqxwmwEnU5r8Q9Lf3ayEzc318CX9bEA5eGHpxl/6xSgAXNZ+HbiQDErHmpuR37VVGynzYv+sHqB/YqUCABe591XMLokzc9Y7S5mTtsN0ecQpLs+DEkxoJ0vw2opE3eLJ2ymwZWpqhbiYsvom/7ZvMAKXx4+6wOiEcK1eMA5Uqp42Pa51a1qweptT0dgYTIXsmYWctsx8swOMBM+alGTgYofQwVnz9J3dy9pn+Dlnp/xXGNc67nzmn2dJxjersLdVKxAg9Us24L36Zof8X9ENqqU6CrKVeqYJEF/YNXVH4SsVPCos7JdZm6rmSKjasKDUrZXDgjlHJuo9CgjjH3K0i+xNw2fDgT0jrNmlj+gYA/EDC6OLDdql/l6kd5R7zVKub00cjsLlcJ/SgEe2lEL6xhr6sAGxOywmCBzR0yZunfVlmMpGR9beuSbqxkiUiD+duNwv6/eHVCGc0kDUs7yvDMLHa2pwkjX2Us=
  app: bfk-portal
