language: csharp
dist: trusty
mono: none
dotnet: 2.1.403
install:
- dotnet restore
script:
- dotnet build
- dotnet test ./BfkPortal.PersistenceTest/BfkPortal.PersistenceTest.csproj
- dotnet test ./BfkPortal.WebTest/BfkPortal.WebTest.csproj
deploy:
  provider: heroku
  api_key:
    secure: gztoVIZ97Y+KwqvukUjMl34tliLGQbZNzDEvbnXB9bHcfdRulS/rvwmGu6m9Qnxu9IXlLdd1zPkra9NDAM0HQBKYzo9/3T02zC7XKcRGTgcJ7olD+UIhT9XScJPPGMzoGDvluNBN2ETTl0zwq5LiUuF+3rSwc3EzUNvoUBNbMMLnlz6eCym16aZcMX2PMKIZEnY/A67xl+hVA/YgAuezBqKX48NrZ7DZAMSPFxgauynNyJfPyuan6xN2L9Tp8jvQCwDJMEaAS4/EX/TZ5P8Jdkn3B2ypBZgJ2vabJOFehVcTCE0is56SWKnqhVpxKhSiKUlRHAwl4IcwUzAqwFCd7YROG8soJeEiZGdyCZv6sDsQZX9fnth3iSkUZS+un2H8SE5uiudFcW4/pAXkWrAgXsCsz6Gi6J/Ivw6nWfXB04WOXShN4En+QbAXli7JiRBY8+hncRnlJLbikA2n06XDXOyqn/8ngJ1/z4921jS4dLeQRKEu2Gcrhpv6JJSWEgDnQn75ozl+juxt9lxGGEe+UOx2uBZIEnArolJBySDV72NrooVQ53SyvtLybPoiMOrCWnEnssV8vJdbbbzMAWMTF4erdBhQiY0sZ4cRdWhppCBVfkhw6fJsgx12Hw3dSscUeW1kJy2zo4pABW77YJOxTB/vlhQgg0AKuDHUqSOnrKY=
  app: bfk-portal
  on:
    repo: ChristophThiel/bfk-portal-server
