namespace BfkPortal.Core.Models.Enums
{
    public enum PreferenceType
    {
        FirstMonday = 0,
        FirstTuesday,
        FirstWednesday,
        FirstThursday,
        FirstFriday,
        FirstSaturday,
        FirstSunday,
        SecondMonday,
        SecondTuesday,
        SecondWednesday,
        SecondThursday,
        SecondFriday,
        SecondSaturday,
        SecondSunday,
        ThirdMonday,
        ThirdTuesday,
        ThirdWednesday,
        ThirdThursday,
        ThirdFriday,
        ThirdSaturday,
        ThirdSunday,
        FourthMonday,
        FourthTuesday,
        FourthWednesday,
        FourthThursday,
        FourthFriday,
        FourthSaturday,
        FourthSunday,
        January,
        Feburary,
        March,
        April,
        May,
        June,
        July,
        August,
        September,
        October,
        November,
        December,
        Holiday,
        Weekend

        /*ShiftCount = 0,
        AvoidHoliday,
        FixShift,
        AvoidFirstDays,
        AvoidShiftTypes,
        AvoidDays,
        AvoidMonths */
    }
}
